#!/usr/bin/env php
<?php
/*
 * 控制台入口
 */

require(dirname(__DIR__) . '/vendor/autoload.php');

use LumengPHP\Console\Application;
use LumengPHP\Console\Commands\JobWorkerCommand;

$app = new Application(__DIR__ . '/config/config.php');

$app->add(new JobWorkerCommand());

$app->run();

