#!/usr/bin/env php
<?php
/*
 * 安装及初始化LumengPHP应用
 */

/**
 * 打印使用方式
 */
function print_usage() {
    echo "Usage:\n";
    echo "    lumeng-php new <VendorName>/<ProjectName>\n";
    echo "Example:\n";
    echo "    lumeng-php new Apache/Blog\n";
}

//应用根目录
$appDir = getcwd();

if ($_SERVER['argc'] <> 3) {
    echo "参数错误！\n";
    print_usage();
    exit(-1);
}

if ($_SERVER['argv'][1] <> 'new') {
    echo "参数错误！\n";
    print_usage();
    exit(-1);
}

list($vendorName, $projectName) = explode('/', $_SERVER['argv'][2]);
if (empty($vendorName) || empty($projectName)) {
    echo "参数错误！\n";
    print_usage();
    exit(-1);
}

$vendorName = ucfirst($vendorName);
$projectName = ucfirst($projectName);

//目录权限
$mode = 0755;

//要创建的目录列表
$makingDirList = array(
    "{$appDir}/config",
    "{$appDir}/resources",
    "{$appDir}/resources/views",
    "{$appDir}/src",
    "{$appDir}/src/{$vendorName}",
    "{$appDir}/src/{$vendorName}/$projectName",
    "{$appDir}/src/{$vendorName}/$projectName/Commands",
    "{$appDir}/src/{$vendorName}/$projectName/Models",
    "{$appDir}/web",
    "{$appDir}/web/static",
    "{$appDir}/web/static/js",
    "{$appDir}/web/static/css",
    "{$appDir}/web/static/images",
    "{$appDir}/tests",
    "{$appDir}/tests/config",
    "{$appDir}/tests/TestCases",
    "{$appDir}/tests/resources",
    "{$appDir}/var",
    "{$appDir}/var/cache",
    "{$appDir}/var/logs",
);

foreach ($makingDirList as $makingDir) {
    mkdir($makingDir, $mode);
}

//安装程序模板文件目录
$tplDir = __DIR__ . '/templates';

//待复制的模板文件
$copyingFiles = array(
    '/config/config.php',
    '/config/database.php',
    '/config/extensions.php',
    '/config/filter.php',
    '/config/parameters.php',
    '/config/routing.php',
    '/config/services.php',
    '/src/VendorName/ProjectName/Commands/HomeCommand.php',
    '/web/.htaccess',
    '/web/index.php',
    '/tests/bootstrap.php',
    '/tests/config/config.php',
    '/tests/TestCases/BaseDatabaseTestCase.php',
    '/console',
);

//复制各文件
foreach ($copyingFiles as $copyingFile) {
    $src = $tplDir . $copyingFile;

    $targetFile = $copyingFile;
    if (strpos($copyingFile, '/src') === 0) {
        $targetFile = str_replace('/VendorName/ProjectName', "/{$vendorName}/{$projectName}", $copyingFile);
    }

    $target = $appDir . $targetFile;

    copy($src, $target);

    if ($targetFile == '/config/routing.php' || strpos($targetFile, '/src') === 0) {
        $content = file_get_contents($target);
        $actualContent = str_replace('VendorName\\ProjectName', "{$vendorName}\\{$projectName}", $content);
        file_put_contents($target, $actualContent);
    }
}

//设置console文件为可执行
chmod($appDir . '/console', 0755);

//更新composer.json文件，
$composerJsonPath = $appDir . '/composer.json';
$composerJson = json_decode(file_get_contents($composerJsonPath), true);
//增加autoload配置
$composerJson['autoload']['psr-4']["{$vendorName}\\{$projectName}\\"] = "src/{$vendorName}/{$projectName}/";
//设置实际的根命名空间及其目录路径
$composerJson['namespace-root'] = "{$vendorName}\\{$projectName}\\";
$composerJson['namespace-root-dir'] = "src/{$vendorName}/{$projectName}/";
//保存更改
file_put_contents($composerJsonPath, json_encode($composerJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");

//更新autoload
$cmd = "composer --working-dir={$appDir} dump-autoload";
exec($cmd);

echo "应用创建成功！\n";
