#!/usr/bin/env php
<?php
/*
 * 安装及初始化LumengPHP应用
 */

/**
 * 打印使用方式
 */
function print_usage() {
    echo "Usage:\n";
    echo "    mkdir <project-name>\n";
    echo "    cd <project-name>\n";
    echo "    composer require lumeng/lumeng-php\n";
    echo "    php install <VendorName>/<ProjectName>\n";
    echo "Example:\n";
    echo "    mkdir blog\n";
    echo "    cd blog\n";
    echo "    composer require lumeng/lumeng-php\n";
    echo "    php install Apache/Blog\n";
}

//应用根目录
$appDir = dirname(dirname(dirname(dirname(__DIR__))));

if ($_SERVER['argc'] <> 2) {
    echo "参数错误！\n";
    print_usage();
    exit(-1);
}

list($vendorName, $projectName) = explode('/', $_SERVER['argv'][1]);
if (empty($vendorName) || empty($projectName)) {
    echo "参数错误！\n";
    print_usage();
    exit(-1);
}

$vendorName = ucfirst($vendorName);
$projectName = ucfirst($projectName);

//目录权限
$mode = 0755;

//要创建的目录列表
$makingDirList = array(
    "{$appDir}/bin",
    "{$appDir}/config",
    "{$appDir}/resources",
    "{$appDir}/resources/views",
    "{$appDir}/src",
    "{$appDir}/src/{$vendorName}",
    "{$appDir}/src/{$vendorName}/$projectName",
    "{$appDir}/src/{$vendorName}/$projectName/Commands",
    "{$appDir}/src/{$vendorName}/$projectName/Models",
    "{$appDir}/web",
    "{$appDir}/web/static",
    "{$appDir}/web/static/js",
    "{$appDir}/web/static/css",
    "{$appDir}/web/static/images",
    "{$appDir}/tests",
    "{$appDir}/tests/config",
    "{$appDir}/tests/TestCases",
    "{$appDir}/var",
    "{$appDir}/var/cache",
    "{$appDir}/var/logs",
);

foreach ($makingDirList as $makingDir) {
    mkdir($makingDir, $mode);
}

//安装程序模板文件目录
$tplDir = __DIR__ . '/templates';

//待复制的模板文件
$copyingFiles = array(
    '/config/config.php',
    '/config/database.php',
    '/config/extensions.php',
    '/config/filter.php',
    '/config/parameters.php',
    '/config/routing.php',
    '/config/services.php',
    '/src/VendorName/ProjectName/Commands/HomeCommand.php',
    '/web/.htaccess',
    '/web/index.php',
);

foreach ($copyingFiles as $copyingFile) {
    $src = $tplDir . $copyingFile;

    $targetFile = $copyingFile;
    if (strpos($copyingFile, '/src') === 0) {
        $targetFile = str_replace('/VendorName/ProjectName', "/{$vendorName}/{$projectName}", $copyingFile);
    }

    $target = $appDir . $targetFile;

    copy($src, $target);

    if ($targetFile == '/config/routing.php' || strpos($targetFile, '/src') === 0) {
        $content = file_get_contents($target);
        $actualContent = str_replace('VendorName\ProjectName', "{$vendorName}\\{$projectName}", $content);
        file_put_contents($target, $actualContent);
    }
}

//更新composer.json文件，增加autoload配置
$composerJsonPath = $appDir . '/composer.json';
$composerJson = json_decode(file_get_contents($composerJsonPath), true);
$composerJson['autoload']['psr-4']["{$vendorName}\\{$projectName}\\"] = "src/{$vendorName}/{$projectName}/";
file_put_contents($composerJsonPath, json_encode($composerJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");

//更新autoload
$cmd = "composer --working-dir={$appDir} dump-autoload";
exec($cmd);

echo "应用创建成功！\n";
